Divers corrections
Plutonium-Mcpe/pluto-wiki pull request #45
Opened 2022-08-03 15:01 UTC by xEditedNewt

Rien de fou, de petites choses corrigées

2022-08-07 10:43 UTC, ShockedPlot7560 requested changes
Quelques modifications nécessaires

2022-08-07 10:43 UTC, ShockedPlot7560 commented on docs/events-auto/totem.md
> +Lorsque l'évent commence, votre objectif est de détruire le totem sans que ce processus de destruction soit interrompu par un joueur d'une autre faction.
```suggestion
Lorsque l'événement commence, votre objectif est de détruire le totem sans que ce processus de destruction soit interrompu par un joueur d'une autre faction.  
```

2022-08-07 10:43 UTC, ShockedPlot7560 commented on docs/events-auto/totem.md
> +Cela vous prendra du temps de casser l'ensemble les blocs du totem auto se trouve au milieu de l'arène. Ainsi, il faut que votre faction vous protège afin d'empêcher les autres factions d'interrompre
```suggestion
Cela vous prendra du temps de casser l'ensemble les blocs du totem qui se trouve au milieu de l'arène. Ainsi, il faut que votre faction vous protège afin d'empêcher les autres factions d'interrompre votre capture du totem.  
```

2022-08-07 10:43 UTC, ShockedPlot7560 commented on docs/events-auto/totem.md
> +Faites attention, les autres factions peuvent réinitialiser votre avancée uniquement en commençant à miner le totem à votre place. Se sera ensuite à vous de tenter de réinitialiser leur progression p
```suggestion
Faites attention, les autres factions peuvent réinitialiser votre avancée uniquement en débutant à miner le totem. Se sera ensuite à vous de tenter de réinitialiser leur progression pour tenter de remporter l'événement en détruisant totalement le totem.  
```

2022-08-07 10:43 UTC, ShockedPlot7560 commented on docs/events-auto/totem.md
> +**Pour les vainqueurs** : entre 500 et 1500 STR pour la faction du vainceur.
```suggestion
**Pour les vainqueurs** : entre 500 et 1500 power pour la faction du vainqueur.
```

2022-08-11 16:50 UTC, xEditedNewt commented on docs/events-auto/totem.md
> +**Pour les vainqueurs** : entre 500 et 1500 STR pour la faction du vainceur.
Parfait

2022-08-21 17:26 UTC, merged