Divers modifications
Plutonium-Mcpe/pluto-wiki pull request #47
Opened 2022-08-03 15:16 UTC by xEditedNewt

2022-08-07 10:50 UTC, ShockedPlot7560 requested changes
Nécessite quelque modifications

2022-08-07 10:50 UTC, ShockedPlot7560 commented on docs/help/spawner.md
> +Les spawners sont des blocs vanilla permettant de générer reguli et de manière continue la créature ou l'animal qui se trouve dans lui.
```suggestion
Les spawners sont des blocs vanilla permettant de générer régulièrement et de manière continue le monstre ou l'animal qui se trouve dans lui.  
```

2022-08-07 10:50 UTC, ShockedPlot7560 commented on docs/help/spawner.md
> +Néanmoins, un système différent de gestion et d'utilisation des spawners est en place sur le serveur.
```suggestion
Néanmoins, un système différent de génération et de d'utilisation des spawners a été mis en place sur le serveur.    
```

2022-08-07 10:50 UTC, ShockedPlot7560 commented on docs/help/spawner.md
> +Les spawners sont donc dès à présent automatiquement  générée sur les maps des différents serveurs factions. Les spawners se trouvent dans des salles comportant entre 1 et 4 spawners.
```suggestion
Les spawners sont donc dès à présent automatiquement générée sur les maps des différents serveurs factions. Les spawners se trouvent dans des salles comportant entre 1 et 4 spawners.  
```

2022-08-11 16:54 UTC, xEditedNewt commented on docs/help/spawner.md
> +Néanmoins, un système différent de gestion et d'utilisation des spawners est en place sur le serveur.
Étant donné que la génération est continue le présent c’était mieux non ? 
Après ça change pas grand chose comme tu veux

2022-08-11 18:07 UTC, ShockedPlot7560 commented on docs/help/spawner.md
> +Néanmoins, un système différent de gestion et d'utilisation des spawners est en place sur le serveur.
Le système a été mis en place, on ne la pas mit aujourd'hui mais il y a quelques mois donc je pense que cette formulation est mieux.
Cependant dans ma suggestion il y a une répétition se de, d'

2022-08-14 14:41 UTC, merged