issue lucky réglé
Plutonium-Mcpe/pluto-wiki pull request #61
Opened 2022-09-21 15:13 UTC by ClueXIII

2022-09-21 15:14 UTC, ShockedPlot7560 commented on docs/blocs/lucky-block.md
> +|           {{image#blocks/fire_1_placeholder}                 Allumer le feu            |                                           Met en feu la zone autour du lucky block
```suggestion
|           {{image#blocks/fire_1_placeholder}}                 Allumer le feu            |                                           Met en feu la zone autour du lucky block                                           |   3,41 %    |
```

2022-09-21 15:14 UTC, ShockedPlot7560 commented on docs/blocs/lucky-block.md
> +### Mettez tout en jeux pour tenter de tout gagner avec les lucky blocks !
Plutôt que de mettre un titre, pour question d'optimisation SEO, il serait mieux de soit mettre un embed, soit du gras mais pas de titre

2022-09-21 15:15 UTC, ShockedPlot7560 commented on docs/blocs/lucky-block.md
> +### Mettez tout en jeux pour tenter de tout gagner avec les lucky blocks !
Pour ce qui concerne le commentaire en dessous de description

2022-09-21 15:17 UTC, ShockedPlot7560 commented
Fix de l'issue: 
- #60

2022-09-25 09:06 UTC, ShockedPlot7560 commented
@ClueXIII il reste des modifications en attente

2022-09-26 05:31 UTC, ShockedPlot7560 requested changes

2022-09-26 05:31 UTC, ShockedPlot7560 commented on docs/blocs/lucky-block.md
> +<img class="thumbnail-right" src="textures/blocks/others/lucky_tophee_full.png">
Ce lien ne fonctionneras pas

2022-10-21 17:46 UTC, xEditedNewt commented on docs/blocs/lucky-block.md
> +<img class="thumbnail-right" src="textures/blocks/others/lucky_tophee_full.png">
@ClueXIII Si tu as la flemme : https://user-images.githubusercontent.com/91474741/197257381-925586a1-6e87-467c-b308-38e8eb51a989.png

2022-12-19 13:05 UTC, QuentinGrnr commented
je ne comprend pas, j'ai comit et merge mais la verif se base sur l'ancien fichier

2022-12-19 13:15 UTC, ShockedPlot7560 commented
> je ne comprend pas, j'ai comit et merge mais la verif se base sur l'ancien fichier

Dans l'icône de l'en-tête

2022-12-19 13:47 UTC, ClueXIII commented
> 

l'erreur est sur le chemin vers le trophé lucky, non le lucky de l'entéte

2022-12-19 13:57 UTC, ShockedPlot7560 commented
> > 
> 
> l'erreur est sur le chemin vers le trophé lucky, non le lucky de l'entéte

L'erreur est bien sur l'en tête de l'article, il n'y a plus qu'à cet endroit que dans le fichier il y a ce lien ci

2022-12-19 14:05 UTC, ClueXIII commented
> > > 
> > 
> > 
> > l'erreur est sur le chemin vers le trophé lucky, non le lucky de l'entéte
> 
> L'erreur est bien sur l'en tête de l'article, il n'y a plus qu'à cet endroit que dans le fichier il y a ce lien ci
> 
> ![image](https://user-images.githubusercontent.com/66992287/208442061-146e20bb-e46b-490c-bf59-809f9b11ec7e.png)

![image](https://user-images.githubusercontent.com/109299545/208443249-dfed0b41-f6d1-421e-9236-4d5813c1e462.png)
mais l'erreur vise "textures/blocks/others/lucky_tophee_full.png" pas "textures/blocks/others/lucky_block.png".

2022-12-19 14:08 UTC, ShockedPlot7560 commented
Oui en effet, les tests semblent prendre les anciens fichier, je vérifierais de mon côté avant de merge tout de même.

2022-12-29 14:58 UTC, merged