Ajout salon kit & parchemin, harmonisation warzone
Plutonium-Mcpe/pluto-wiki pull request #66
Opened 2022-09-23 21:50 UTC by xEditedNewt

2022-09-25 07:28 UTC, ShockedPlot7560 requested changes

2022-09-25 07:28 UTC, ShockedPlot7560 commented on docs/commands/kit.md
> +Suprême Légende | Grade Légende | 1 clé Suprême | 5j
Pour tout les kits, il serait bien de mettre un visuel avec les items directement dans le coffre, tout en gardant une liste.

2022-09-25 07:28 UTC, ShockedPlot7560 commented on docs/items/parchment.md
> +Les parchemins sont des items magiques rares qui sont associés à des récompenses uniques et variées. Il existe à ce jour 10 parchemins différents offrant une récompense plus ou moins utile et rare su
Plutôt que évent, j'aurais plutot mis événement

2022-09-25 07:28 UTC, ShockedPlot7560 commented on docs/items/parchment.md
> +* ``Fonctionnement`` : Vous donne un accès à pour utiliser la commande ``/rename {texte}``. Cette commande vous permet de modifier le nom d'un item en ce que vous souhaitez. Vous devez ainsi effectue
Il serait bien de préciser que certains items et certains nom sont soumis à restriction

2022-09-25 07:28 UTC, ShockedPlot7560 commented on docs/items/parchment.md
> +Nombre | Couleur
```suggestion
Symbole | Couleur
```

2022-09-25 07:28 UTC, ShockedPlot7560 commented on docs/items/parchment.md
> +* ``Fonctionnement`` : Ce parchemin permet de changer la couleur de vos messages sur le serveur. Pour ceci, il faut mettre le symbole § suivi d'un chiffre allant de 0 à 9. Voici un tableau qui associ
Il y a aussi des lettres pour les couleurs du chat.
Fournir l'image ? 
![image](https://user-images.githubusercontent.com/66992287/192132829-f2abe53c-b39e-490e-98e1-87f4c33704a0.png)

2022-09-25 07:28 UTC, ShockedPlot7560 commented on docs/items/parchment.md
> +* ``Fonctionnement`` : Lorsque vous utilisez ce parchemin, vous recevez directement le grade Aventurier et donc tous les avantages qui sont liés avec ce grade [ #commandes/grade].
Mettre un avertissement que si l'on a un grade supérieur à aventurier, style légende, celui ci sera supprimé ?

2022-09-25 07:28 UTC, ShockedPlot7560 commented on docs/items/parchment.md
> +* ``Fonctionnement`` : Lorsque vous utilisez ce parchemin, vous recevez directement le grade VIP et donc tous les avantages qui sont liés avec ce grade [ #commandes/grade].
Idem pour ce grade

2022-09-25 07:28 UTC, ShockedPlot7560 commented on docs/items/parchment.md
> +### {{image#items/others/parchment}} Parchemin Titan
Idem pour ce grade

2022-09-25 07:28 UTC, ShockedPlot7560 commented on docs/items/parchment.md
> +* ``Fonctionnement`` : Vous donne l'équivalent du nombre d'xp nécessaire pour passer de 0 à 50, soit 5 345 xp dans votre bar d'xp.
```suggestion
* ``Fonctionnement`` : Vous donne l'équivalent du nombre d'xp nécessaire pour passer de 0 à 50, soit 5 345 xp dans votre barre d'xp.
```

2022-09-25 07:28 UTC, ShockedPlot7560 commented on docs/items/parchment.md
> +* ``Fonctionnement`` : Vous donne l'équivalent du nombre d'xp nécessaire pour passer de 0 à 100 soit 30 970 xp dans votre bar d'xp.
```suggestion
* ``Fonctionnement`` : Vous donne l'équivalent du nombre d'xp nécessaire pour passer de 0 à 100 soit 30 970 xp dans votre barre d'xp.
```

2022-09-25 07:28 UTC, ShockedPlot7560 commented on docs/items/parchment.md
> +### {{image#items/others/parchment}} Parchemin 100 level
```suggestion
### {{image#items/others/parchment}} Parchemin 100 levels
```

2022-09-25 07:28 UTC, ShockedPlot7560 commented on docs/tools/sword.md
> +> Nécessite le niveau 4 du métier #help/bucheron
Métier de guerrier et non bûcheron

2022-09-25 07:28 UTC, ShockedPlot7560 commented on docs/commands/kit.md
> +Suprême Légende | Grade Légende | 1 clé Suprême | 5j
Et donc on retirerait le tableau pour mettre des titres à la place

2022-09-25 09:42 UTC, xEditedNewt commented on docs/tools/sword.md
> +> Nécessite le niveau 4 du métier #help/bucheron
Modification effectuée

2022-09-25 09:43 UTC, xEditedNewt commented on docs/items/parchment.md
> +### {{image#items/others/parchment}} Parchemin 100 level
Modification effectuée

2022-09-25 09:43 UTC, xEditedNewt commented on docs/items/parchment.md
> +* ``Fonctionnement`` : Vous donne l'équivalent du nombre d'xp nécessaire pour passer de 0 à 100 soit 30 970 xp dans votre bar d'xp.
Modification effectuée

2022-09-25 09:43 UTC, xEditedNewt commented on docs/items/parchment.md
> +* ``Fonctionnement`` : Vous donne l'équivalent du nombre d'xp nécessaire pour passer de 0 à 50, soit 5 345 xp dans votre bar d'xp.
Modification effectuée

2022-09-25 09:43 UTC, xEditedNewt commented on docs/items/parchment.md
> +### {{image#items/others/parchment}} Parchemin Titan
Modification effectuée

2022-09-25 09:43 UTC, xEditedNewt commented on docs/items/parchment.md
> +* ``Fonctionnement`` : Ce parchemin permet de changer la couleur de vos messages sur le serveur. Pour ceci, il faut mettre le symbole § suivi d'un chiffre allant de 0 à 9. Voici un tableau qui associ
Modification effectuée

2022-09-25 09:43 UTC, xEditedNewt commented on docs/items/parchment.md
> +* ``Fonctionnement`` : Lorsque vous utilisez ce parchemin, vous recevez directement le grade Aventurier et donc tous les avantages qui sont liés avec ce grade [ #commandes/grade].
Modification effectuée

2022-09-25 09:43 UTC, xEditedNewt commented on docs/items/parchment.md
> +Nombre | Couleur
Modification effectuée

2022-09-25 09:43 UTC, xEditedNewt commented on docs/items/parchment.md
> +* ``Fonctionnement`` : Vous donne un accès à pour utiliser la commande ``/rename {texte}``. Cette commande vous permet de modifier le nom d'un item en ce que vous souhaitez. Vous devez ainsi effectue
Modification effectuée

2022-09-25 09:43 UTC, xEditedNewt commented on docs/items/parchment.md
> +Les parchemins sont des items magiques rares qui sont associés à des récompenses uniques et variées. Il existe à ce jour 10 parchemins différents offrant une récompense plus ou moins utile et rare su
Modification effectuée

2022-09-25 09:43 UTC, xEditedNewt commented on docs/commands/kit.md
> +Suprême Légende | Grade Légende | 1 clé Suprême | 5j
Modification effectuée

2022-09-25 09:47 UTC, ShockedPlot7560 requested changes

2022-09-25 09:47 UTC, ShockedPlot7560 commented on docs/commands/kit.md
> +
Manque un screen

2022-09-25 09:47 UTC, ShockedPlot7560 commented on docs/commands/kit.md
> +### Kit Suprême Titan
Inutile là, il faut le joindre au titan

2022-09-25 09:47 UTC, ShockedPlot7560 commented on docs/commands/kit.md
> +### Kit Suprême Légende
idem que le titan

2022-09-25 09:47 UTC, ShockedPlot7560 commented on docs/items/parchment.md
> +> Si vous utilisez ce parchemin alors que vous avez déjà un grade supérieur à Ttan, celui si sera supprimé.
```suggestion
> Si vous utilisez ce parchemin alors que vous avez déjà un grade supérieur à Titan, celui si sera supprimé. 
```

2022-09-25 09:48 UTC, xEditedNewt commented on docs/commands/kit.md
> +### Kit Suprême Légende
Dans le /kit ig, ils sont séparés

2022-09-25 09:50 UTC, ShockedPlot7560 commented on docs/commands/kit.md
> +### Kit Suprême Légende
Oui mais nous ne sommes pas ig :)  
Il faut juste préciser que une clé suprême est disponible différement du kit

2022-09-25 09:50 UTC, xEditedNewt commented on docs/commands/kit.md
> +### Kit Suprême Légende
Et c'est galère de dire que le kit de base c'est 48h et qu'il y a un autre kit titan tous les 10 j dans la même partie

2022-09-26 05:31 UTC, ShockedPlot7560 commented on docs/commands/kit.md
> +### Kit Suprême Légende
Galère mais obligatoire dans ce cas

2022-09-26 20:58 UTC, ShockedPlot7560 requested changes

2022-09-26 20:58 UTC, ShockedPlot7560 commented on docs/commands/kit.md
> +![image](https://user-images.githubusercontent.com/91474741/192136847-6aa7e8e2-d492-4fc8-92ae-6bf8dd1e1109.png)
Entre les crochets, il serait préferable de mettre ce que l'image représente, en l'occurrence: Kit joueur. Et ce pour tout les kits

2022-09-26 20:58 UTC, ShockedPlot7560 commented on docs/commands/kit.md
> +``Kit suprême Titan`` : 1 clé Suprême accessible toutes les 10 jours
```suggestion
``Contenu spécial`` : 1 clé Suprême accessible toutes les 10 jours    
```

2022-09-26 20:58 UTC, ShockedPlot7560 commented on docs/commands/kit.md
> +``Kit suprême Légende`` : 1 clé Suprême accessible toutes les 5 jours
```suggestion
``Contenu spécial`` : 1 clé Suprême accessible toutes les 5 jours    
```

2022-09-27 16:55 UTC, xEditedNewt commented on docs/commands/kit.md
> +``Kit suprême Titan`` : 1 clé Suprême accessible toutes les 10 jours
Il faut bien le séparer de l'autre kit, car ce n'est pas exactement le même, ça porte à confusion "contenu spécial"

2022-09-27 17:20 UTC, ShockedPlot7560 commented on docs/commands/kit.md
> +``Kit suprême Titan`` : 1 clé Suprême accessible toutes les 10 jours
Est-ce vraiment un kit autre ??

2022-09-27 17:21 UTC, xEditedNewt commented on docs/commands/kit.md
> +``Kit suprême Titan`` : 1 clé Suprême accessible toutes les 10 jours
Il est séparé du kit titan normal, donc oui un peu

2022-09-27 17:22 UTC, ShockedPlot7560 commented on docs/commands/kit.md
> +``Kit suprême Titan`` : 1 clé Suprême accessible toutes les 10 jours
Ok et bien j'ai rien dit, désolé, on le sépare

2022-09-29 08:03 UTC, ShockedPlot7560 commented
Les clés suprême sont toujours fusionnées avec les kits de bases

2022-09-29 15:47 UTC, ShockedPlot7560 requested changes
Enlever la ligne screen car on voit que c'est un screen, laisser l'image à la suite du contenu.

2022-09-29 15:47 UTC, ShockedPlot7560 commented on docs/commands/kit.md
> +``Condition pour y accéder`` : Aucun
```suggestion
``Condition pour y accéder`` : Aucune  
```

2022-09-29 15:47 UTC, ShockedPlot7560 commented on docs/commands/kit.md
> +``Condition pour y accéder`` : Aucun
```suggestion
``Condition pour y accéder`` : Aucune  
```

2022-09-29 15:47 UTC, ShockedPlot7560 commented on docs/commands/kit.md
> +``Screen`` :
Enlever la ligne screen car on voit que c'est un screen, laisser l'image à la suite du contenu. Faire de même pour la suite

2022-09-30 05:26 UTC, ShockedPlot7560 approved these changes

2022-09-30 16:46 UTC, merged