Create box.md
Plutonium-Mcpe/pluto-wiki pull request #70
Opened 2022-09-28 15:00 UTC by xEditedNewt

Issues #65

2022-09-28 15:04 UTC, xEditedNewt commented
Je n'ai pas capté... 
Pk je peux pas appeler box.md ?

2022-09-28 15:47 UTC, ShockedPlot7560 commented
> Je n'ai pas capté... Pk je peux pas appeler box.md ?

Tente de ne pas mettre le ``&`` mais directement et ?  
Ou bien vérifie si la texture existe bien.

2022-09-28 18:57 UTC, xEditedNewt commented
non la texture est bonne, je ne trouve pas le problème la

2022-09-29 08:00 UTC, ShockedPlot7560 commented
Après vérification, il y a un espace en trop après les guillemets fermant du champ ``icon``.

2022-09-29 15:44 UTC, ShockedPlot7560 requested changes
Pas mal d'oublie de ``s`` et changer les key en clé.

2022-09-29 15:44 UTC, ShockedPlot7560 commented on docs/help/box.md
> +Pour ouvrire une box, il faut tout d'abord avoir une #items/key correspondant à la box que vous souhaitez ouvrir. Il suffit ensuite de cliquer sur la box avec cette key puis faire joueur votre chance
```suggestion
Pour ouvrir une box, il faut tout d'abord avoir une #items/key correspondant à la box que vous souhaitez ouvrir. Il suffit ensuite de cliquer sur la box avec cette clé puis faire jouer votre chance ! 
```

2022-09-29 15:44 UTC, ShockedPlot7560 commented on docs/help/box.md
> +{{image#items/seeds/opalite_seed}} 5 Graine d'opalite | 20%
```suggestion
{{image#items/seeds/opalite_seed}} 5 Graines d'opalite | 20%
```

2022-09-29 15:44 UTC, ShockedPlot7560 commented on docs/help/box.md
> +{{image#items/keys/opalite_key}} 1 Key opalite | 2%
```suggestion
{{image#items/keys/opalite_key}} 1 Clé opalite | 2%  
```

2022-09-29 15:44 UTC, ShockedPlot7560 commented on docs/help/box.md
> +{{image#items/keys/common_key}} 1 Key commune | 3%
```suggestion
{{image#items/keys/common_key}} 1 Clé commune | 3%
```

2022-09-29 15:44 UTC, ShockedPlot7560 commented on docs/help/box.md
> +{{image#blocks/diamond_block}} 16 Bloc de diamant | 3%
```suggestion
{{image#blocks/diamond_block}} 16 Blocs de diamant | 3%
```

2022-09-29 15:44 UTC, ShockedPlot7560 commented on docs/help/box.md
> +{{image#blocks/iron_block}}16 Bloc de fer | 13%
```suggestion
{{image#blocks/iron_block}} 16s Bloc de fer | 13%
```

2022-09-29 15:44 UTC, ShockedPlot7560 commented on docs/help/box.md
> +{{image#items/keys/plutonium_key}} 1 Key Plutonium | 1%
```suggestion
{{image#items/keys/plutonium_key}} 1 Clé Plutonium | 1%  
```

2022-09-29 15:44 UTC, ShockedPlot7560 commented on docs/help/box.md
> +{{image#items/seeds/plutonium_seed}}64 Graine de Plutonium | 29%
```suggestion
{{image#items/seeds/plutonium_seed}}64 Graines de Plutonium | 29%
```

2022-09-29 15:44 UTC, ShockedPlot7560 commented on docs/help/box.md
> +{{image#items/ores/plutonium_dust}} 6 Poussière de Plutonium | 10%
Beaucoup de ``s`` manquant

2022-09-29 15:44 UTC, ShockedPlot7560 commented on docs/help/box.md
> +{{image#items/keys/plutonium_key}} 1 Key Plutonium | 2.5%
Changer les key en clé, car on est français ici :)

2022-09-29 15:46 UTC, xEditedNewt commented on docs/help/box.md
> +{{image#items/seeds/opalite_seed}} 5 Graine d'opalite | 20%
J'ai mis aucun pluriel, car j'ai pris les noms sur Minecraft des item ( je vais d'ailleurs créer une issue à ce sujet )

2022-09-29 15:48 UTC, ShockedPlot7560 commented on docs/help/box.md
> +{{image#items/seeds/opalite_seed}} 5 Graine d'opalite | 20%
Oui il faudrait harmoniser tout les pluriels, car là c'est normal de mettre au pluriel le mot graine

2022-09-30 05:26 UTC, ShockedPlot7560 approved these changes

2022-09-30 16:48 UTC, merged