Harmonisation écriture Wiki Blocs
Plutonium-Mcpe/pluto-wiki pull request #75
Opened 2022-10-01 12:19 UTC by xEditedNewt

Catégorie Blocs
Issues #72 
Diverse petites corrections

2022-10-01 21:58 UTC, ShockedPlot7560 requested changes

2022-10-01 21:58 UTC, ShockedPlot7560 commented on docs/blocs/drawer.md
> +- ``Stockage ``: 2 500 items
```suggestion
- ``Stockage`` : 2 500 items 
```

2022-10-01 21:58 UTC, ShockedPlot7560 commented on docs/blocs/drawer.md
> +- ``Stockage ``: 2 500 items
Et pour tout les autres en dessous

2022-10-01 21:58 UTC, ShockedPlot7560 commented on docs/blocs/xp-collector.md
>  - ``Conversion ``: 25k XP = level 0 -> level 100
```suggestion
- ``Conversion`` : 25k XP = level 0 -> level 100 
```

2022-10-01 21:58 UTC, ShockedPlot7560 commented on docs/blocs/xp-collector.md
>  - ``Conversion ``: 25k XP = level 0 -> level 100
Et pour tout ceux du dessus

2022-11-23 17:40 UTC, xEditedNewt commented
Normalement terminé

2022-11-24 05:07 UTC, ShockedPlot7560 approved these changes

2022-11-25 17:33 UTC, merged