Harmonisation écriture Wiki Boss
Plutonium-Mcpe/pluto-wiki pull request #76
Opened 2022-10-01 12:28 UTC by xEditedNewt

Catégorie Boss
Issues #72  
Diverse petites corrections

2022-10-01 22:02 UTC, ShockedPlot7560 requested changes

2022-10-01 22:02 UTC, ShockedPlot7560 commented on docs/boss/alpha.md
> +- ``Points de vie`` : 50 000 points de vie
Mettre l'image du coeur ici ?

2022-10-01 22:02 UTC, ShockedPlot7560 commented on docs/boss/beta.md
> +- ``Points de vie`` : 25 000 points de vie
Mettre l'image du coeur je pense ici

2022-10-01 22:02 UTC, ShockedPlot7560 commented on docs/boss/gamma.md
> +- ``Points de vie`` : 10 000 points de vie
Idem, image du coeur

2022-10-01 22:07 UTC, xEditedNewt commented on docs/boss/alpha.md
> +- ``Points de vie`` : 50 000 points de vie
Il a 50k coeurs ?

2022-10-01 22:10 UTC, ShockedPlot7560 commented on docs/boss/alpha.md
> +- ``Points de vie`` : 50 000 points de vie
Alors, si il en a 50k ca serait en PV et non coeur. Mais le nombre serais à vérifier. Une mise à jour il a quelque semaine avait touché les boss et probablement leurs statistiques

2022-10-01 22:13 UTC, xEditedNewt commented on docs/boss/alpha.md
> +- ``Points de vie`` : 50 000 points de vie
Je met les coeurs du coup ? 
Et pour vérifier les stats, je te laisse faire j'ai pas les accès x)

2022-10-01 22:14 UTC, ShockedPlot7560 commented on docs/boss/alpha.md
> +- ``Points de vie`` : 50 000 points de vie
diviser par deux et mes les coeurs oui, pour les stats je ferais une issue si besoin

2022-10-02 16:05 UTC, ShockedPlot7560 approved these changes

2022-10-02 16:20 UTC, merged