Create clean-stick.md
Plutonium-Mcpe/pluto-wiki pull request #86
Opened 2022-10-24 18:14 UTC by xEditedNewt

2022-10-29 09:16 UTC, ShockedPlot7560 requested changes

2022-10-29 09:16 UTC, ShockedPlot7560 commented on docs/items/clean-stick.md
> +* ``Blocs supprimés :`` Blocs de Terre & blocs de Pierre
Ce ne sont pas les seuls: 
- Granite
- Andésite
- Diorite
- Cobblestone et non la pierre

2022-10-29 09:16 UTC, ShockedPlot7560 commented on docs/items/clean-stick.md
> +* ``Durabilité:`` 10 utilisations
25 utilisations et non 10

2022-10-29 09:16 UTC, ShockedPlot7560 commented on docs/items/clean-stick.md
> +* ``Cooldown:`` 30 secondes entre chaque utilisation
Il n'y a pas de cooldown sur cet item

2022-11-23 17:43 UTC, xEditedNewt commented
Normalement terminé

2022-11-24 05:09 UTC, ShockedPlot7560 approved these changes

2022-11-25 17:32 UTC, merged