Create tnt.md
Plutonium-Mcpe/pluto-wiki pull request #91
Opened 2022-11-25 08:45 UTC by xEditedNewt

#37

2022-11-25 17:16 UTC, ShockedPlot7560 requested changes

2022-11-25 17:16 UTC, ShockedPlot7560 commented on docs/blocs/tnt.md
> +Les TNT moddées fonctionnent exactement comme la tnt classique mais avec un rayon d'action bien plus important. Plus le niveau de la TNT est élevé, plus les dégâts seront importants.
Il faut choisir, entre mettre TNT en majuscule ou non, mais on va essayer de ne pas mélanger

2022-11-25 17:16 UTC, ShockedPlot7560 commented on docs/blocs/tnt.md
> +Ne jouez pas trop avec ces blocs, ils peuvent rapidement devenir incontrôlable !!
```suggestion
Ne jouez pas trop avec ces blocs, ils peuvent rapidement devenir incontrôlables !! 
```

2022-11-25 17:16 UTC, ShockedPlot7560 commented on docs/blocs/tnt.md
> +## {{image#blocks/tnts/lvl2/tnt_lvl2_side}} TNT level 2 :
```suggestion
## {{image#blocks/tnts/lvl2/tnt_lvl2_side}} TNT de niveau 2 :
```
Le faire pour tout le reste

2022-11-25 17:16 UTC, ShockedPlot7560 commented on docs/blocs/tnt.md
> +- ``Zone de dégâts`` : Zone de 10 blocs
Rayon d'explosion de 7 blocs

2022-11-25 17:16 UTC, ShockedPlot7560 commented on docs/blocs/tnt.md
> +- ``Zone de dégâts`` : Zone de 15 blocs
Rayon de 12 blocs

2022-11-25 17:16 UTC, ShockedPlot7560 commented on docs/blocs/tnt.md
> +- ``Zone de dégâts`` : Zone de 20 blocs
21 blocs de rayon

2022-11-25 17:16 UTC, ShockedPlot7560 commented on docs/blocs/tnt.md
> +- ``Zone de dégâts`` : Zone de 30 blocs
37 blocs de rayon

2022-11-25 17:16 UTC, ShockedPlot7560 commented on docs/blocs/tnt.md
> +- ``Zone de dégâts`` : Zone de 40 blocs
55 blocs de rayons

2022-11-25 17:16 UTC, ShockedPlot7560 commented on docs/blocs/tnt.md
> +- ``Zone de dégâts`` : Zone de 50 blocs
80 blocs de rayon

2022-11-25 17:16 UTC, ShockedPlot7560 commented on docs/blocs/tnt.md
> +- ``Zone de dégâts`` : Zone de 60 blocs
135 blocs de rayons

2022-11-25 17:16 UTC, ShockedPlot7560 commented on docs/blocs/tnt.md
> +- ``Zone de dégâts`` : Zone de 80 blocs
180 blocs de rayon

2022-11-25 17:16 UTC, ShockedPlot7560 commented on docs/blocs/tnt.md
> +> Aucun niveau spécial de métier est nécessaire pour l’utilisation & craft du four.
Modifier ce copier coller non modifié, ici et partout

2022-11-25 17:27 UTC, ShockedPlot7560 commented
Workflow correct, script indiquant du faux positif

2022-11-25 19:48 UTC, xEditedNewt commented
Le truc pour les claim c'est correcte ?

2022-11-26 11:15 UTC, CleSucre commented
Oui c'est parfait, a partir des tnt niveau 6 elles ne casse plus dans les claim.

2022-11-27 14:01 UTC, merged

2022-11-27 16:26 UTC, ShockedPlot7560 commented
> Oui c'est parfait, a partir des tnt niveau 6 elles ne casse plus dans les claim.

Bah du coup ce n'était pas parfait ;-; le niveau 2 est marqué comme cassable dans les claims

2022-11-28 13:06 UTC, CleSucre commented
> > Oui c'est parfait, a partir des tnt niveau 6 elles ne casse plus dans les claim.
> 
> Bah du coup ce n'était pas parfait ;-; le niveau 2 est marqué comme cassable dans les claims

Du niveau 1-5, les TNT cassent bel et bien dans les claims
Du niveau 6-9, les TNT ne peuvent pas être explosés trop proche des claims/protections pour ne pas les cassez. Donc elle ne casse pas dans les clailm ;)