Mise à jour Noël
Plutonium-Mcpe/pluto-wiki pull request #93
Opened 2022-11-30 10:57 UTC by xEditedNewt

2022-11-30 10:59 UTC, xEditedNewt commented
Problème provient du pack de texture normalement

2022-11-30 11:04 UTC, ShockedPlot7560 commented
> Problème provient du pack de texture normalement 

Non, ce n'est pas ce que les tests disent.

2022-11-30 12:40 UTC, xEditedNewt commented
C'est good maintenant

2022-12-03 11:11 UTC, ShockedPlot7560 commented
Je t"invite à mettre à jour, j'ai mis à jour le pack de texture

2022-12-03 11:14 UTC, ShockedPlot7560 commented
Etonnant, les modifications de nöel sont pour certaine déjà présente

2022-12-03 17:42 UTC, ShockedPlot7560 requested changes

2022-12-03 17:42 UTC, ShockedPlot7560 commented on docs/blocs/christmas-gift.md
> +| {{image#items/armors/opalite/opalite_boots}} Une pair de botte en Opalite  (enchantement protection 4) |    1,5 %    |
Corriger une faute pour en laisser une ...

2022-12-03 17:42 UTC, ShockedPlot7560 commented on docs/blocs/christmas-gift.md
> +|                    {{image#items/armors/farm/farm_leggings}} Des jambierres de farm                    |    1,5 %    |
Corriger une faute pour en laisser une ...

2022-12-03 17:42 UTC, ShockedPlot7560 commented on docs/items/christmas-ball.md
> +description: boule de noel
```suggestion
description: Item pour PvP il permettra d'immobiliser votre adversaire
```

2022-12-03 17:42 UTC, ShockedPlot7560 commented on docs/items/christmas-star.md
> +-``Durée l'annimation`` : X secondes
Inutile

2022-12-03 17:42 UTC, ShockedPlot7560 commented on docs/items/infinity-snowball.md
> +Cette item est une sorte de boule de neige compacté, elle a donc exactement le même fonctionnement qu'une boule de neiges classique mais avec beaucoup plus d'utilisation. Pratique pour réduire la pla
```suggestion
Cette item est une sorte de boule de neige compacté, elle a donc exactement le même fonctionnement qu'une boule de neige classique mais avec beaucoup plus d'utilisation. Pratique pour réduire la place des boules de neiges dans votre inventaire !
```

2022-12-03 17:42 UTC, ShockedPlot7560 commented on docs/items/sandals.md
> +description: Les sandales magiques permettent de marcher sur l'eau
Le principe a été changé, les scandales rajoute désormais des couches de neiges en dessous du joueur.  
L'article est donc à modifier

2022-12-06 09:34 UTC, developtc commented
Metter à jour le wiki svp

2022-12-09 17:34 UTC, merged